Machine_Lending_Management_System/urls.py
from django.contrib import admin
from django.urls import *
from django.views.generic import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('machines/', include('machines.urls')),
    path("", RedirectView.as_view(url="machines/")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('panel/', include('panel.urls')),
    path('userlist/', include("usermanager.urls"))
]

machines/urls.py
from django.urls import *
from .views import *
from django.views.generic import *

urlpatterns = [
    path('laptop/', LaptopList.as_view(), name='laptop_list'),
    path("add_item/", addMachine.as_view(), name="add_machine"),
    path("other/", OtherList.as_view(), name="other_list"),
    path("", RedirectView.as_view(url="laptop/"))
]

panel/urls.py
from django.urls import path
from .views import Userinfo, Panel

urlpatterns = [
    path('', Panel.as_view()),
    path('userinfo/', Userinfo.as_view()),
]

usermanager/urls.py
from django.urls import *
from .views import *
from django.views.generic import *

urlpatterns = [
    path('', RedirectView.as_view(url="inschool/")),
    path('inschool/',InSchool.as_view(),name="inschool_list"),
    path('left/', Left.as_view(),name="left_list")
]

machines/models.py
from django.db import models

# Create your models here.


class MachineItem(models.Model):
    machine_status = [
        (0, "使用中"),
        (1, "無人使用"),
        (2, "已報廢")
    ]

    machine_type = [
        (0, "筆電"),
        (1, "其他設備")
    ]

    type_of_machine = models.IntegerField(
        "設備類型", default=0, choices=machine_type)

    brand = models.CharField("設備型號", max_length=20)

    boughtdate = models.DateField("購買日期", auto_now=False)

    details = models.TextField("詳細規格")

    now_machine_status = models.IntegerField(
        "目前狀態", default=0, choices=machine_status)

    machine_number = models.CharField("設備編號", max_length=9)

    item_number = models.CharField("財產編號", max_length=17)

    note = models.TextField("備註")

    def __str__(self):
        return self.brand

panel/models.py
from django.db import models

# Create your models here.

usermanager/models.py
from django.db import models

# Create your models here.


class Teacher(models.Model):
    stay = [
        (0, "在職"),
        (1, "已離職")
    ]
    name = models.CharField("姓名", max_length=4)

    stay_choose = models.IntegerField(
        "在職狀態", default=0, choices=stay
    )

machines/forms.py
from django import forms
from .models import *


class addMachineForm(forms.ModelForm):
    class Meta:
        model = MachineItem
        fields = ["type_of_machine", "brand", "machine_number",
                  "item_number", "boughtdate",  "details", "note"]
        widgets = {
            "type_of_machine": forms.Select(
                attrs={
                    "class": "mt-2 mb-2"
                }
            ),
            "brand": forms.TextInput(
                attrs={
                    "class": "form-control mt-2 mb-2"
                }
            ),
            "machine_number": forms.TextInput(
                attrs={
                    "class": "form-control mt-2 mb-2"
                }
            ),
            "item_number": forms.TextInput(
                attrs={
                    "class": "form-control mt-2 mb-2"
                }
            ),
            "boughtdate": forms.TextInput(
                attrs={
                    "class": "datepicker"
                }
            ),
            "details": forms.Textarea(
                attrs={
                    "class": "form-control mt-2 mb-2"
                }
            ),
            "note": forms.Textarea(
                attrs={
                    "class": "form-control mt-2 mb-2"
                }
            )
        }

usermanager/forms.py
from django import forms
from .models import *

class addTeacherForm(forms.ModelForm):
    class Meta:
        model=Teacher
        fields=["name","stay_choose"]
        widgets={
            "name":forms.TextInput(
                attrs={
                    "class":"form-control mt-2 mb-2" 
                }
            ),
            "stay_choose":forms.Select(
                attrs={
                    "class":"form-control mt-2 mb-2"    
                }
            )
        }

machines/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import *
from .models import *
from .forms import *
import random

# Create your views here.


class LaptopList(ListView):
    model = MachineItem
    template_name = "machines/machine_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_title'] = "筆電列表"
        context['type_of_machine'] = "筆電"
        return context


class OtherList(ListView):
    model = MachineItem
    template_name = "machines/machine_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_title'] = "其他設備列表"
        context['type_of_machine'] = "其他設備"
        return context


class addMachine(CreateView):
    model = MachineItem
    #fields = ["brand", "boughtdate", "details", "note","type_of_machine"]
    form_class = addMachineForm
    template_name = "machines/machineitem_form.html"

    def get_success_url(self):
        return reverse("laptop_list")

panel/views.py
from django.shortcuts import render

# Create your views here.


from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
# Create your views here.


class Panel(LoginRequiredMixin, TemplateView):
    template_name = "panel.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = '儀表板'
        return context


class Userinfo(LoginRequiredMixin, TemplateView):
    template_name = "userinfo.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = '使用者資訊'
        return context

usermanager/views.py
from django.shortcuts import render
from django.views.generic import *
from django.urls import *
from django.contrib.auth.models import *
from django.contrib.auth.mixins import *
from .models import *
from .forms import *

# Create your views here.

class InSchool(ListView):
    model = Teacher
    template_name = "userlist.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "在職"
        return context


class Left(ListView):
    model = Teacher
    template_name = "userlist.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "已離職"
        return context


class addTeacher(CreateView):
    template_name = "addteacher.html"
    model = Teacher
    form_class=addTeacherForm

    def get_success_url(self):
        return reverse("inschool_list")

machines/templates/base.html
<html lang="zh-hants">

<head>
    <link rel="stylesheet" href="/static/customstyle.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
        integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <style>

    </style>
    <title>設備借用管理系統</title>
</head>

<body>
    {% include "navbar.html" %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>

</html>

machines/templates/machines/machine_list.html
{% extends "base.html" %}

{% block content %}
<div class="mb-2 mt-4">
    <h1 class="">{{ list_title }}</h1>
    {% if user.is_authenticated %}
        <a type="button" href="/machines/add_item" class="btn btn-success mt-2 ml-auto">新增裝置</a>
    {% endif %}
</div>

<table class="striped centered responsive-table">
    <thead class="thead-dark">
        <tr>
            <th>設備型號</th>
            <th>借出狀態</th>
            <th>詳細資訊</th>
        </tr>
    </thead>
    <tbody>
        {% for item in machineitem_list %}
        {% if item.get_type_of_machine_display == type_of_machine %}
        <tr>
            <td>
                {{ item.brand }}
            </td>
            <td>{{ item.get_now_machine_status_display }}</td>
            <td>{{ item.details }}</td>
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
</table>
{% endblock %}

machines/templates/machines/machineitem_form.html
{% extends "base.html" %}

{% block content %}
<script>
  $(document).ready(() => {
    $('select').formSelect();
    $('.datepicker').datepicker({
      format:"yyyy-mm-dd"
    });
    $(document).find("textarea").addClass("materialize-textarea");
  });

</script>
<h1 class="h1 mt-4 mb-4">新增設備</h1>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table class="table table-sm">
    {{ form.as_table }}
  </table>
  <input class="btn btn-hg btn-primary btn-block" type="submit" value="送出" />
</form>
{% endblock %}

machines/templates/navbar.html
<script>
  $(() => {
    $(document).ready(() => {
      $(".dropdown-trigger").dropdown();
      $('.sidenav').sidenav();
    });
  });
</script>

<ul id="machinedropdown1" class="dropdown-content">
  <li><a href="/machines/laptop">筆電</a></li>
  <li><a href="/machines/other">其他設備</a></li>
</ul>

<ul id="machinedropdown2" class="dropdown-content">
  <li><a href="/machines/laptop">筆電</a></li>
  <li><a href="/machines/other">其他設備</a></li>
</ul>

<ul id="userlistdropdown1" class="dropdown-content">
  <li><a href="/userlist/inschool">在職</a></li>
  <li><a href="/userlist/left">已離校</a></li>
</ul>

<ul id="userlistdropdown2" class="dropdown-content">
  <li><a href="/userlist/inschool">在職</a></li>
  <li><a href="/userlist/left">已離校</a></li>
</ul>

<nav>
  <div class="nav-wrapper">
    <a href="/" class="brand-logo">設備借用管理系統</a>
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><a class="dropdown-trigger" href="#!" data-target="machinedropdown1">機型列表<i
            class="material-icons right">arrow_drop_down</i></a></li>
      <li><a class="dropdown-trigger" href="#!" data-target="userlistdropdown1">借用人列表<i
            class="material-icons right">arrow_drop_down</i></a></li>
      {% if user.is_authenticated %}
      <li>
        <a href="/panel">
          <i class="material-icons left">person</i> {{ user.username }}
        </a>
      </li>
      <li>
        <a href="{% url 'logout' %}" class="waves-effect waves-light btn">
          <i class="material-icons left">exit_to_app</i> 登出
        </a>
      </li>
      {% else %}
      <li>
        <a href="{% url 'login' %}" class="waves-effect waves-light btn">
          <i class="material-icons left">login</i> 登入
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

<ul class="sidenav" id="mobile-demo">
  <li><a class="dropdown-trigger" href="#!" data-target="machinedropdown2">機型列表<i
        class="material-icons right">arrow_drop_down</i></a></li>
  <li><a class="dropdown-trigger" href="#!" data-target="userlistdropdown2">借用人列表<i
        class="material-icons right">arrow_drop_down</i></a></li>
  {% if user.is_authenticated %}
  <li>
    <a href="/panel">
      <i class="material-icons left">person</i> {{ user.username }}
    </a>
  </li>
  <li>
    <a href="{% url 'logout' %}" class="waves-effect waves-light btn">
      <i class="material-icons left">exit_to_app</i> 登出
    </a>
  </li>
  {% else %}
  <li>
    <a href="{% url 'login' %}" class="waves-effect waves-light btn">
      <i class="material-icons left">login</i> 登入
    </a>
  </li>
  {% endif %}
</ul>

panel/templates/panel.html
{% extends "base.html" %}
{% block content %}
<div>
  <div class="col">
    <div class="card">
      <div class="card-content">
        <span class="card-title"><i class="fas fa-id-card-alt mb-2"></i> 使用者簡單資料</span>
        <table class="striped">
          <tbody>
            <tr>
              <td>使用者名稱</td>
              <td>{{user.username}}</td>
            </tr>
            <tr>
              <td>帳號申請日期</td>
              <td>{{user.date_joined}}</td>
            </tr>
            <tr>
              <td>最後登入日期</td>
              <td>{{user.last_login}}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="card-action">
        <div class="btn-group row" role="group" aria-label="Basic example">
          <a class="btn btn-primary" href="/"><i class="fas fa-home"></i> 首頁</a>
          <a class="btn btn-secondary" href="/admin/"><i class="fas fa-database"></i> 查看資料庫</a>
          <a class="btn btn-secondary" href="userinfo/"><i class="fas fa-id-card"></i> 使用者詳細資料</a>
          <a class="btn btn-secondary" href="{% url 'logout' %}" type="button"><i class="fas fa-sign-out-alt"></i>登出</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

panel/templates/userinfo.html
{% extends "base.html" %}
{% block content %}
<h2 class="font-weight-bold mb-4 mt-4">{{title}}</h2>
<table class="table table-striped table-hover container">
    <thead class="thead-dark">
        <tr>
            <th scope="col">項目</th>
            <th scope="col">內容</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>使用者名稱</td>
            <td>{{user.username}}</td>
        </tr>
        <tr>
            <td>姓氏</td>
            <td>{{user.last_name}}</td>
        </tr>
        <tr>
            <td>名字</td>
            <td>{{user.first_name}}</td>
        </tr>
        <tr>
            <td>電子郵件</td>
            <td>{{user.email}}</td>
        </tr>
        <tr>
            <td>使用者群組</td>
            <td>{{user.groups}}</td>
        </tr>
        <tr>
            <td>使用者權限</td>
            <td>{{user.user_permissions}}</td>
        </tr>
        <tr>
            <td>是否為工作人員</td>
            {% if user.is_staff %}
            <td>是</td>
            {% else %}
            <td>否</td>
            {% endif %}
        </tr>
        <tr>
            <td>是否為超級使用者</td>
            {% if user.is_superuser %}
            <td>是</td>
            {% else %}
            <td>否</td>
            {% endif %}
        </tr>
        <tr>
            <td>帳戶啟用狀態</td>
            {% if user.is_active %}
            <td>已啟用</td>
            {% else %}
            <td>未啟用</td>
            {% endif %}
        </tr>
        <tr>
            <td>帳號申請日期</td>
            <td>{{user.date_joined}}</td>
        </tr>
        <tr>
            <td>最後登入日期</td>
            <td>{{user.last_login}}</td>
        </tr>
    </tbody>
</table>

<a class="waves-effect waves-light btn" href="{% url 'logout' %}">
    <i class="fas fa-sign-out-alt"></i>登出
</a>
{% endblock content %}

usermanager/templates/userlist.html
{% extends "base.html" %}

{% block content %}
    
{% endblock %}